#Mock data used to test first normal form and is after sensitive info removed, contains 10 dictionaries

list_of_dicts = [{'date_time': '09/05/2023 09:00', 'branch_location': 'Leeds', 'order_details_string': 'Regular Iced americano - 2.15, Large Hot Chocolate - 1.70, Regular Iced americano - 2.15, Large Filter coffee - 1.80', 'payment_total': '7.8', 'payment_type': 'CARD', 'id': 0}, 
{'date_time': '09/05/2023 09:01', 'branch_location': 'Leeds', 'order_details_string': 'Large Chai latte - 2.60, Regular Hot Chocolate - 1.40', 'payment_total': '4.0', 'payment_type': 'CASH', 'id': 1},
{'date_time': '09/05/2023 09:03', 'branch_location': 'Leeds', 'order_details_string': 'Regular Chai latte - 2.30, Regular Filter coffee - 1.50, Large Chai latte - 2.60', 'payment_total': '6.4', 'payment_type': 'CARD', 'id': 2},
{'date_time': '09/05/2023 09:04', 'branch_location': 'Leeds', 'order_details_string': 'Regular Iced americano - 2.15, Regular Hot Chocolate - 1.40', 'payment_total': '3.55', 'payment_type': 'CARD', 'id': 3},
{'date_time': '09/05/2023 09:06', 'branch_location': 'Leeds', 'order_details_string': 'Large Speciality Tea - English breakfast - 1.60, Regular Filter coffee - 1.50, Regular Speciality Tea - English breakfast - 1.30', 'payment_total': '4.4', 'payment_type': 'CASH', 'id': 4}, 
{'date_time': '09/05/2023 09:08', 'branch_location': 'Leeds', 'order_details_string': 'Regular Speciality Tea - English breakfast - 1.30, Large Chai latte - 2.60, Large Hot Chocolate - 1.70, Regular Speciality Tea - English breakfast - 1.30', 'payment_total': '6.9', 'payment_type': 'CARD', 'id': 5},
{'date_time': '09/05/2023 09:09', 'branch_location': 'Leeds', 'order_details_string': 'Regular Chai latte - 2.30, Regular Filter coffee - 1.50, Large Hot Chocolate - 1.70', 'payment_total': '5.5', 'payment_type': 'CARD', 'id': 6},
{'date_time': '09/05/2023 09:11', 'branch_location': 'Leeds', 'order_details_string': 'Regular Chai latte - 2.30, Large Filter coffee - 1.80, Large Filter coffee - 1.80', 'payment_total': '5.9', 'payment_type': 'CASH', 'id': 7},
{'date_time': '09/05/2023 09:12', 'branch_location': 'Leeds', 'order_details_string': 'Regular Filter coffee - 1.50, Regular Hot Chocolate - 1.40', 'payment_total': '2.9', 'payment_type': 'CARD', 'id': 8},
{'date_time': '09/05/2023 09:14', 'branch_location': 'Leeds', 'order_details_string': 'Regular Chai latte - 2.30', 'payment_total': '2.3', 'payment_type': 'CARD', 'id': 9}]

#Mock data used to test second normal form, is the above data if passed through first normal form, contains 27 dictionaries

list_of_dicts_1nf = [{'date_time': '09/05/2023 09:00', 'branch_location': 'Leeds', 'order_details_string': 'Regular Iced americano - 2.15', 'payment_total': '7.8', 'payment_type': 'CARD', 'id': 0},
 {'date_time': '09/05/2023 09:00', 'branch_location': 'Leeds', 'order_details_string': ' Large Hot Chocolate - 1.70', 'payment_total': '7.8', 'payment_type': 'CARD', 'id': 0},
 {'date_time': '09/05/2023 09:00', 'branch_location': 'Leeds', 'order_details_string': ' Regular Iced americano - 2.15', 'payment_total': '7.8', 'payment_type': 'CARD', 'id': 0},
 {'date_time': '09/05/2023 09:00', 'branch_location': 'Leeds', 'order_details_string': ' Large Filter coffee - 1.80', 'payment_total': '7.8', 'payment_type': 'CARD', 'id': 0},
 {'date_time': '09/05/2023 09:01', 'branch_location': 'Leeds', 'order_details_string': 'Large Chai latte - 2.60', 'payment_total': '4.0', 'payment_type': 'CASH', 'id': 1},
 {'date_time': '09/05/2023 09:01', 'branch_location': 'Leeds', 'order_details_string': ' Regular Hot Chocolate - 1.40', 'payment_total': '4.0', 'payment_type': 'CASH', 'id': 1},
 {'date_time': '09/05/2023 09:03', 'branch_location': 'Leeds', 'order_details_string': 'Regular Chai latte - 2.30', 'payment_total': '6.4', 'payment_type': 'CARD', 'id': 2},
 {'date_time': '09/05/2023 09:03', 'branch_location': 'Leeds', 'order_details_string': ' Regular Filter coffee - 1.50', 'payment_total': '6.4', 'payment_type': 'CARD', 'id': 2},
 {'date_time': '09/05/2023 09:03', 'branch_location': 'Leeds', 'order_details_string': ' Large Chai latte - 2.60', 'payment_total': '6.4', 'payment_type': 'CARD', 'id': 2},
 {'date_time': '09/05/2023 09:04', 'branch_location': 'Leeds', 'order_details_string': 'Regular Iced americano - 2.15', 'payment_total': '3.55', 'payment_type': 'CARD', 'id': 3},
 {'date_time': '09/05/2023 09:04', 'branch_location': 'Leeds', 'order_details_string': ' Regular Hot Chocolate - 1.40', 'payment_total': '3.55', 'payment_type': 'CARD', 'id': 3},
 {'date_time': '09/05/2023 09:06', 'branch_location': 'Leeds', 'order_details_string': 'Large Speciality Tea - English breakfast - 1.60', 'payment_total': '4.4', 'payment_type': 'CASH', 'id': 4},
 {'date_time': '09/05/2023 09:06', 'branch_location': 'Leeds', 'order_details_string': ' Regular Filter coffee - 1.50', 'payment_total': '4.4', 'payment_type': 'CASH', 'id': 4},
 {'date_time': '09/05/2023 09:06', 'branch_location': 'Leeds', 'order_details_string': ' Regular Speciality Tea - English breakfast - 1.30', 'payment_total': '4.4', 'payment_type': 'CASH', 'id': 4},
 {'date_time': '09/05/2023 09:08', 'branch_location': 'Leeds', 'order_details_string': 'Regular Speciality Tea - English breakfast - 1.30', 'payment_total': '6.9', 'payment_type': 'CARD', 'id': 5},
 {'date_time': '09/05/2023 09:08', 'branch_location': 'Leeds', 'order_details_string': ' Large Chai latte - 2.60', 'payment_total': '6.9', 'payment_type': 'CARD', 'id': 5},
 {'date_time': '09/05/2023 09:08', 'branch_location': 'Leeds', 'order_details_string': ' Large Hot Chocolate - 1.70', 'payment_total': '6.9', 'payment_type': 'CARD', 'id': 5},
 {'date_time': '09/05/2023 09:08', 'branch_location': 'Leeds', 'order_details_string': ' Regular Speciality Tea - English breakfast - 1.30', 'payment_total': '6.9', 'payment_type': 'CARD', 'id': 5},
 {'date_time': '09/05/2023 09:09', 'branch_location': 'Leeds', 'order_details_string': 'Regular Chai latte - 2.30', 'payment_total': '5.5', 'payment_type': 'CARD', 'id': 6},
 {'date_time': '09/05/2023 09:09', 'branch_location': 'Leeds', 'order_details_string': ' Regular Filter coffee - 1.50', 'payment_total': '5.5', 'payment_type': 'CARD', 'id': 6},
 {'date_time': '09/05/2023 09:09', 'branch_location': 'Leeds', 'order_details_string': ' Large Hot Chocolate - 1.70', 'payment_total': '5.5', 'payment_type': 'CARD', 'id': 6},
 {'date_time': '09/05/2023 09:11', 'branch_location': 'Leeds', 'order_details_string': 'Regular Chai latte - 2.30', 'payment_total': '5.9', 'payment_type': 'CASH', 'id': 7},
 {'date_time': '09/05/2023 09:11', 'branch_location': 'Leeds', 'order_details_string': ' Large Filter coffee - 1.80', 'payment_total': '5.9', 'payment_type': 'CASH', 'id': 7},
 {'date_time': '09/05/2023 09:11', 'branch_location': 'Leeds', 'order_details_string': ' Large Filter coffee - 1.80', 'payment_total': '5.9', 'payment_type': 'CASH', 'id': 7},
 {'date_time': '09/05/2023 09:12', 'branch_location': 'Leeds', 'order_details_string': 'Regular Filter coffee - 1.50', 'payment_total': '2.9', 'payment_type': 'CARD', 'id': 8},
 {'date_time': '09/05/2023 09:12', 'branch_location': 'Leeds', 'order_details_string': ' Regular Hot Chocolate - 1.40', 'payment_total': '2.9', 'payment_type': 'CARD', 'id': 8},
 {'date_time': '09/05/2023 09:14', 'branch_location': 'Leeds', 'order_details_string': 'Regular Chai latte - 2.30', 'payment_total': '2.3', 'payment_type': 'CARD', 'id': 9}]

#Mock data used to test third normal form, is the above data is passed through second normal form, contains 27 dictionaries

list_of_dicts_2nf = [{'date_time': '09/05/2023 09:00', 'branch_location': 'Leeds', 'payment_total': '7.8', 'payment_type': 'CARD', 'id': 0, 'product_name': 'Regular Iced americano', 'product_price': '2.15'},
{'date_time': '09/05/2023 09:00', 'branch_location': 'Leeds', 'payment_total': '7.8', 'payment_type': 'CARD', 'id': 0, 'product_name': 'Large Hot Chocolate', 'product_price': '1.70'},
{'date_time': '09/05/2023 09:00', 'branch_location': 'Leeds', 'payment_total': '7.8', 'payment_type': 'CARD', 'id': 0, 'product_name': 'Regular Iced americano', 'product_price': '2.15'},
{'date_time': '09/05/2023 09:00', 'branch_location': 'Leeds', 'payment_total': '7.8', 'payment_type': 'CARD', 'id': 0, 'product_name': 'Large Filter coffee', 'product_price': '1.80'},
{'date_time': '09/05/2023 09:01', 'branch_location': 'Leeds', 'payment_total': '4.0', 'payment_type': 'CASH', 'id': 1, 'product_name': 'Large Chai latte', 'product_price': '2.60'},
{'date_time': '09/05/2023 09:01', 'branch_location': 'Leeds', 'payment_total': '4.0', 'payment_type': 'CASH', 'id': 1, 'product_name': 'Regular Hot Chocolate', 'product_price': '1.40'},
{'date_time': '09/05/2023 09:03', 'branch_location': 'Leeds', 'payment_total': '6.4', 'payment_type': 'CARD', 'id': 2, 'product_name': 'Regular Chai latte', 'product_price': '2.30'},
{'date_time': '09/05/2023 09:03', 'branch_location': 'Leeds', 'payment_total': '6.4', 'payment_type': 'CARD', 'id': 2, 'product_name': 'Regular Filter coffee', 'product_price': '1.50'},
{'date_time': '09/05/2023 09:03', 'branch_location': 'Leeds', 'payment_total': '6.4', 'payment_type': 'CARD', 'id': 2, 'product_name': 'Large Chai latte', 'product_price': '2.60'},
{'date_time': '09/05/2023 09:04', 'branch_location': 'Leeds', 'payment_total': '3.55', 'payment_type': 'CARD', 'id': 3, 'product_name': 'Regular Iced americano', 'product_price': '2.15'},
{'date_time': '09/05/2023 09:04', 'branch_location': 'Leeds', 'payment_total': '3.55', 'payment_type': 'CARD', 'id': 3, 'product_name': 'Regular Hot Chocolate', 'product_price': '1.40'},
{'date_time': '09/05/2023 09:06', 'branch_location': 'Leeds', 'payment_total': '4.4', 'payment_type': 'CASH', 'id': 4, 'product_name': 'Large Speciality Tea - English breakfast', 'product_price': '1.60'},
{'date_time': '09/05/2023 09:06', 'branch_location': 'Leeds', 'payment_total': '4.4', 'payment_type': 'CASH', 'id': 4, 'product_name': 'Regular Filter coffee', 'product_price': '1.50'},
{'date_time': '09/05/2023 09:06', 'branch_location': 'Leeds', 'payment_total': '4.4', 'payment_type': 'CASH', 'id': 4, 'product_name': 'Regular Speciality Tea - English breakfast', 'product_price': '1.30'},
{'date_time': '09/05/2023 09:08', 'branch_location': 'Leeds', 'payment_total': '6.9', 'payment_type': 'CARD', 'id': 5, 'product_name': 'Regular Speciality Tea - English breakfast', 'product_price': '1.30'},
{'date_time': '09/05/2023 09:08', 'branch_location': 'Leeds', 'payment_total': '6.9', 'payment_type': 'CARD', 'id': 5, 'product_name': 'Large Chai latte', 'product_price': '2.60'},
{'date_time': '09/05/2023 09:08', 'branch_location': 'Leeds', 'payment_total': '6.9', 'payment_type': 'CARD', 'id': 5, 'product_name': 'Large Hot Chocolate', 'product_price': '1.70'},
{'date_time': '09/05/2023 09:08', 'branch_location': 'Leeds', 'payment_total': '6.9', 'payment_type': 'CARD', 'id': 5, 'product_name': 'Regular Speciality Tea - English breakfast', 'product_price': '1.30'},
{'date_time': '09/05/2023 09:09', 'branch_location': 'Leeds', 'payment_total': '5.5', 'payment_type': 'CARD', 'id': 6, 'product_name': 'Regular Chai latte', 'product_price': '2.30'},
{'date_time': '09/05/2023 09:09', 'branch_location': 'Leeds', 'payment_total': '5.5', 'payment_type': 'CARD', 'id': 6, 'product_name': 'Regular Filter coffee', 'product_price': '1.50'},
{'date_time': '09/05/2023 09:09', 'branch_location': 'Leeds', 'payment_total': '5.5', 'payment_type': 'CARD', 'id': 6, 'product_name': 'Large Hot Chocolate', 'product_price': '1.70'},
{'date_time': '09/05/2023 09:11', 'branch_location': 'Leeds', 'payment_total': '5.9', 'payment_type': 'CASH', 'id': 7, 'product_name': 'Regular Chai latte', 'product_price': '2.30'},
{'date_time': '09/05/2023 09:11', 'branch_location': 'Leeds', 'payment_total': '5.9', 'payment_type': 'CASH', 'id': 7, 'product_name': 'Large Filter coffee', 'product_price': '1.80'},
{'date_time': '09/05/2023 09:11', 'branch_location': 'Leeds', 'payment_total': '5.9', 'payment_type': 'CASH', 'id': 7, 'product_name': 'Large Filter coffee', 'product_price': '1.80'},
{'date_time': '09/05/2023 09:12', 'branch_location': 'Leeds', 'payment_total': '2.9', 'payment_type': 'CARD', 'id': 8, 'product_name': 'Regular Filter coffee', 'product_price': '1.50'},
{'date_time': '09/05/2023 09:12', 'branch_location': 'Leeds', 'payment_total': '2.9', 'payment_type': 'CARD', 'id': 8, 'product_name': 'Regular Hot Chocolate', 'product_price': '1.40'},
{'date_time': '09/05/2023 09:14', 'branch_location': 'Leeds', 'payment_total': '2.3', 'payment_type': 'CARD', 'id': 9, 'product_name': 'Regular Chai latte', 'product_price': '2.30'}]